server:
  port: 8090
spring:
  ############################################################
  #
  # 配置邮箱信息
  #
  ############################################################
  mail:
    host: smtp.office365.com  # SMTP 服务器地址
    port: 587
    username: wbt@chessofstars.io # 发送方邮箱地址
    usernameAlias: COSD <cosd@chessofstars.io> # 发送方的邮箱别名
    password: Xiao120315!
    #    username: 13156050650@163.com
    #    password: Xiao120315!
    # 发送方邮箱登录密码或者授权码
    subject: Verification - Chess of Stars
    properties:
      mail:
        #        store:
        #          protocol: pop3
        smtp:
          auth: true  # 开启 SMTP 验证
          starttls:
            enable: true  # 开启 Transport Layer Security (TLS) 加密
  #            required: true
  #          port: 587
  #          socketFactory:
  #            port: 587
  #            fallback: false
  ##            class: javax.net.ssl.SSLSocketFactory
  #          connectiontimeout: 30000
  #          timeout: 30000
  #          writetimeout: 30000
  #        debug: false
  myApp:
    aws:
      ses:
        accessKeyId: AKIASBV7DL66FPX7YGHR
        secretKey: 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
        region: ap-northeast-1
        verifyCodeTemplate: VerifyCodeTemplate-English

