server:
  port: 8090
spring:
  ############################################################
  #
  # 配置邮箱信息
  #
  ############################################################
  mail:
    host: smtp.163.com  # SMTP 服务器地址
    #    port: 465
    username: 13156050650@163.com  # 发送方邮箱地址
    password: GGXCXQBLVCHJULTQ # 发送方邮箱登录密码或者授权码
    subject: Verification - Chess of Stars
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.163.com
          auth: true  # 开启 SMTP 验证
          starttls:
            enable: true  # 开启 Transport Layer Security (TLS) 加密
            required: true
          timeout: 5000  # 连接超时时间
          connectiontimeout: 5000  # 连接超时时间
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
